### ISSUE TITLE
キャラクターのy座標を合わせる

### ISSUE THREAD

**Issue by witalosk** [Noyatsu/dice#22]
単純なプログラムではうまくいかなかった…

**Comment by sasaki-trombone** [comment]
これ昨日やったとき、あくいちゃんの位置にあるサイコロがあればそのサイコロと同じy座標をあくいちゃんに付与することでy座標だけは動いたんだけど、あくいちゃんが操作不能になっちゃった

**Comment by witalosk** [comment]
それな
座標のy成分のみを設定できればいいんだけどねぇ
一気に設定しなきゃいけないからダメ

**Comment by sasaki-trombone** [comment]
yだけ変更したつもりだったんだけどダメだった
